name: U-Net API CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v2

      - name: Configuration de Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Installation des dépendances Python
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Déploiement sur EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Assurez-vous que le répertoire existe ou clonez le dépôt
            if [ ! -d /home/ubuntu/segmentation_cars ]; then
              git clone https://github.com/NetZach777/segmentation_cars.git /home/ubuntu/segmentation_cars
            else
              cd /home/ubuntu/segmentation_cars && git pull
            fi

            # Configuration AWS CLI
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set region ${{ secrets.AWS_REGION }}
            aws configure set output json

            # Création du dossier model et modification des droits
            mkdir -p /home/ubuntu/segmentation_cars/model
            sudo chown -R ubuntu:ubuntu /home/ubuntu/segmentation_cars

            # Téléchargement du modèle depuis S3
            aws s3 cp s3://${{ secrets.BUCKET_NAME }}/unet_light_model_weighted_data_normal.h5 /home/ubuntu/segmentation_cars/model/unet_light_model_weighted_data_normal.h5

            # Déploiement de l'application
            source /home/ubuntu/miniconda3/etc/profile.d/conda.sh
            conda activate unet_api_env
            pip install -r requirements.txt
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &

            # Nettoyage de la clé privée après usage
            # La suppression de la clef n'est plus necessaire, l'action appleboy/ssh-action gère deja cette partie.
