name: Python application CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Installation de Git LFS
      run: |
        sudo apt-get install git-lfs
        git lfs install

    - name: Checkout du code source
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Configuration de Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Installation des dépendances Python
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Installer et ajouter AWS CLI au PATH
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        export PATH=$PATH:/usr/local/bin  # Ajout manuel d'AWS CLI au PATH
        aws --version  # Vérification de l'installation

    - name: Téléchargement du modèle depuis S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1
        HOSTNAME: ${{ secrets.HOST }}
        USER_NAME: ${{ secrets.EC2_USER }}
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          export PATH=$PATH:/usr/local/bin  # Ajout manuel d'AWS CLI au PATH sur EC2
          mkdir -p /home/ubuntu/unet_api/models
          aws s3 cp s3://awsmodelseg/unet_light_model_weighted_data_normal.h5 /home/ubuntu/unet_api/models/unet_light_model_weighted_data_normal.h5
        '
        rm private_key

    - name: Déploiement sur EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOSTNAME: ${{ secrets.HOST }}
        USER_NAME: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          export PATH=$PATH:/usr/local/bin  # Assurez-vous qu'AWS CLI est dans le PATH
          cd /home/ubuntu/unet_api
          source /home/ubuntu/miniconda3/etc/profile.d/conda.sh
          conda activate unet_api_env
          pip install -r requirements.txt
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &
        '
        rm private_key
